# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\".\n\x04ToDo\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"!\n\x11\x43reateToDoRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\"(\n\x0cToDoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.ToDo\"-\n\x10getToDosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.ToDo\"\x08\n\x06MyVoid2\xa6\x01\n\x0bToDoService\x12\x39\n\nCreateToDo\x12\x17.todo.CreateToDoRequest\x1a\x12.todo.ToDoResponse\x12\x30\n\x08GetToDos\x12\x0c.todo.MyVoid\x1a\x16.todo.getToDosResponse\x12*\n\x08\x45\x64itTodo\x12\n.todo.ToDo\x1a\x12.todo.ToDoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=20
  _globals['_TODO']._serialized_end=66
  _globals['_CREATETODOREQUEST']._serialized_start=68
  _globals['_CREATETODOREQUEST']._serialized_end=101
  _globals['_TODORESPONSE']._serialized_start=103
  _globals['_TODORESPONSE']._serialized_end=143
  _globals['_GETTODOSRESPONSE']._serialized_start=145
  _globals['_GETTODOSRESPONSE']._serialized_end=190
  _globals['_MYVOID']._serialized_start=192
  _globals['_MYVOID']._serialized_end=200
  _globals['_TODOSERVICE']._serialized_start=203
  _globals['_TODOSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
