# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import todo_pb2 as todo__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in todo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToDoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateToDo = channel.unary_unary(
                '/todo.ToDoService/CreateToDo',
                request_serializer=todo__pb2.CreateToDoRequest.SerializeToString,
                response_deserializer=todo__pb2.ToDoResponse.FromString,
                _registered_method=True)
        self.GetToDos = channel.unary_unary(
                '/todo.ToDoService/GetToDos',
                request_serializer=todo__pb2.MyVoid.SerializeToString,
                response_deserializer=todo__pb2.getToDosResponse.FromString,
                _registered_method=True)
        self.EditTodo = channel.unary_unary(
                '/todo.ToDoService/EditTodo',
                request_serializer=todo__pb2.ToDo.SerializeToString,
                response_deserializer=todo__pb2.ToDoResponse.FromString,
                _registered_method=True)


class ToDoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateToDo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToDos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToDoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateToDo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateToDo,
                    request_deserializer=todo__pb2.CreateToDoRequest.FromString,
                    response_serializer=todo__pb2.ToDoResponse.SerializeToString,
            ),
            'GetToDos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToDos,
                    request_deserializer=todo__pb2.MyVoid.FromString,
                    response_serializer=todo__pb2.getToDosResponse.SerializeToString,
            ),
            'EditTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.EditTodo,
                    request_deserializer=todo__pb2.ToDo.FromString,
                    response_serializer=todo__pb2.ToDoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todo.ToDoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todo.ToDoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToDoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateToDo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todo.ToDoService/CreateToDo',
            todo__pb2.CreateToDoRequest.SerializeToString,
            todo__pb2.ToDoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToDos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todo.ToDoService/GetToDos',
            todo__pb2.MyVoid.SerializeToString,
            todo__pb2.getToDosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todo.ToDoService/EditTodo',
            todo__pb2.ToDo.SerializeToString,
            todo__pb2.ToDoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
